# ============================================================================
# Sentinel Pro v3.0 — Professional OSINT & Bug Bounty Platform
# Copyright (c) 2026 @who_is_the_black_hat. All rights reserved.
#
# Unauthorized copying, distribution, or modification of this software,
# via any medium, is strictly prohibited without written permission.
# ============================================================================

"""
Report Signature — Sentinel Pro watermark for all generated reports.
"""

from datetime import datetime

TOOL_NAME    = "Sentinel Pro v3.0"
AUTHOR       = "@who_is_the_black_hat"
GITHUB       = "https://github.com/Mrsultan7890/osints"
COPYRIGHT    = f"Copyright (c) 2026 {AUTHOR}. All rights reserved."


def get_signature() -> dict:
    """JSON reports mein add hone wala signature."""
    return {
        "_generated_by": TOOL_NAME,
        "_author":        AUTHOR,
        "_github":        GITHUB,
        "_copyright":     COPYRIGHT,
        "_timestamp":     datetime.now().isoformat(),
        "_warning":       "This report was generated by licensed software. Unauthorized redistribution prohibited.",
    }


def get_html_footer() -> str:
    """HTML reports ke bottom mein add hone wala footer."""
    year = datetime.now().year
    return f"""
<div style="margin-top:40px;padding:16px;background:#0d1117;border-top:1px solid #30363d;
            text-align:center;font-family:'Fira Code',monospace;font-size:0.8em;color:#484f58;">
  <p>Generated by <strong style="color:#58a6ff">{TOOL_NAME}</strong> &nbsp;·&nbsp;
     <a href="{GITHUB}" style="color:#58a6ff;text-decoration:none;">{AUTHOR}</a></p>
  <p style="margin-top:4px;">{COPYRIGHT}</p>
  <p style="margin-top:4px;font-size:0.75em;">
    This report was generated by licensed software.<br>
    Unauthorized copying or redistribution is prohibited.
  </p>
</div>
"""


def get_txt_footer() -> str:
    """Text/summary reports ke bottom mein add hone wala footer."""
    return f"""
{'='*60}
Generated by : {TOOL_NAME}
Author       : {AUTHOR}
GitHub       : {GITHUB}
{COPYRIGHT}
This report was generated by licensed software.
Unauthorized copying or redistribution is prohibited.
{'='*60}
"""


def sign_json(data: dict) -> dict:
    """JSON data mein signature inject karo."""
    signed = dict(data)
    signed['_sentinel'] = get_signature()
    return signed
