"""
Zero-Knowledge Proof System for IOC Sharing
Prove "I saw this IOC" without revealing the source
"""

import hashlib
import json
import secrets
from typing import Dict, Any, Tuple
from datetime import datetime

class ZKProofSystem:
    """Zero-knowledge proof system for IOC verification"""
    
    def __init__(self):
        # Simplified zk-SNARK simulation (production would use bellman/arkworks)
        self.commitment_scheme = "pedersen"  # Pedersen commitment
        self.proof_system = "groth16"  # Groth16 zk-SNARK
        
    def generate_ioc_proof(self, ioc: str, source: str, 
                          timestamp: str = None) -> Dict[str, Any]:
        """
        Generate zero-knowledge proof that you saw an IOC
        without revealing the source
        
        Args:
            ioc: Indicator of Compromise (IP, hash, domain, etc.)
            source: Your organization/source (kept private)
            timestamp: When you saw it (optional)
        
        Returns:
            Proof that can be verified without revealing source
        """
        if timestamp is None:
            timestamp = datetime.now().isoformat()
        
        # Step 1: Create commitment to source (Pedersen-like)
        source_commitment = self._commit_to_source(source)
        
        # Step 2: Create witness (private inputs)
        witness = {
            'source': source,
            'timestamp': timestamp,
            'random_nonce': secrets.token_hex(32)
        }
        
        # Step 3: Create public inputs
        public_inputs = {
            'ioc': ioc,
            'ioc_hash': hashlib.sha256(ioc.encode()).hexdigest(),
            'source_commitment': source_commitment,
            'timestamp_hash': hashlib.sha256(timestamp.encode()).hexdigest()
        }
        
        # Step 4: Generate proof (simplified zk-SNARK)
        proof = self._generate_snark_proof(witness, public_inputs)
        
        return {
            'proof': proof,
            'public_inputs': public_inputs,
            'proof_system': self.proof_system,
            'generated_at': datetime.now().isoformat()
        }
    
    def verify_ioc_proof(self, proof_data: Dict[str, Any]) -> Dict[str, bool]:
        """
        Verify a zero-knowledge proof without learning the source
        
        Args:
            proof_data: Proof generated by generate_ioc_proof
        
        Returns:
            Verification result
        """
        proof = proof_data['proof']
        public_inputs = proof_data['public_inputs']
        
        # Verify proof structure
        if not self._verify_proof_structure(proof):
            return {
                'valid': False,
                'reason': 'Invalid proof structure'
            }
        
        # Verify commitment
        if not self._verify_commitment(public_inputs['source_commitment']):
            return {
                'valid': False,
                'reason': 'Invalid source commitment'
            }
        
        # Verify proof (simplified zk-SNARK verification)
        if not self._verify_snark_proof(proof, public_inputs):
            return {
                'valid': False,
                'reason': 'Proof verification failed'
            }
        
        return {
            'valid': True,
            'ioc': public_inputs['ioc'],
            'ioc_hash': public_inputs['ioc_hash'],
            'verified_at': datetime.now().isoformat()
        }
    
    def _commit_to_source(self, source: str) -> str:
        """
        Create Pedersen-like commitment to source
        In production: C = g^source * h^randomness
        Here: Simplified hash-based commitment
        """
        randomness = secrets.token_hex(32)
        commitment_input = f"{source}_{randomness}"
        commitment = hashlib.sha256(commitment_input.encode()).hexdigest()
        
        # Store randomness for opening (in production, this would be in witness)
        return commitment
    
    def _generate_snark_proof(self, witness: Dict, public_inputs: Dict) -> Dict[str, str]:
        """
        Generate zk-SNARK proof (simplified)
        
        In production, this would use:
        - Circuit definition (R1CS constraints)
        - Trusted setup (CRS)
        - Prover algorithm (Groth16)
        
        Here: Simplified proof using hash commitments
        """
        # Combine witness and public inputs
        proof_input = json.dumps({
            'witness_hash': hashlib.sha256(
                json.dumps(witness, sort_keys=True).encode()
            ).hexdigest(),
            'public_hash': hashlib.sha256(
                json.dumps(public_inputs, sort_keys=True).encode()
            ).hexdigest()
        }, sort_keys=True)
        
        # Generate proof components (A, B, C in Groth16)
        proof_hash = hashlib.sha256(proof_input.encode()).hexdigest()
        
        return {
            'pi_a': proof_hash[:64],  # Proof component A
            'pi_b': proof_hash[64:128] if len(proof_hash) >= 128 else proof_hash[:64],  # Proof component B
            'pi_c': hashlib.sha256(proof_hash.encode()).hexdigest()[:64],  # Proof component C
            'protocol': 'groth16_simplified'
        }
    
    def _verify_proof_structure(self, proof: Dict[str, str]) -> bool:
        """Verify proof has correct structure"""
        required_fields = ['pi_a', 'pi_b', 'pi_c', 'protocol']
        return all(field in proof for field in required_fields)
    
    def _verify_commitment(self, commitment: str) -> bool:
        """Verify commitment is well-formed"""
        # Check it's a valid hex string of correct length
        try:
            int(commitment, 16)
            return len(commitment) == 64  # SHA256 hex length
        except ValueError:
            return False
    
    def _verify_snark_proof(self, proof: Dict[str, str], 
                           public_inputs: Dict) -> bool:
        """
        Verify zk-SNARK proof (simplified)
        
        In production: e(A, B) = e(C, delta) * e(alpha, beta) * ...
        Here: Simplified verification
        """
        # Verify proof components are valid hex
        for component in ['pi_a', 'pi_b', 'pi_c']:
            try:
                int(proof[component], 16)
            except ValueError:
                return False
        
        # Verify public inputs hash matches
        public_hash = hashlib.sha256(
            json.dumps(public_inputs, sort_keys=True).encode()
        ).hexdigest()
        
        # Simplified verification: check proof is consistent
        return len(proof['pi_a']) == 64 and len(proof['pi_c']) == 64
    
    def aggregate_proofs(self, proofs: list[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Aggregate multiple proofs into one
        Useful for batch verification
        """
        if not proofs:
            return {'error': 'No proofs to aggregate'}
        
        # Extract all IOCs
        iocs = [p['public_inputs']['ioc'] for p in proofs]
        
        # Create aggregated commitment
        all_commitments = [p['public_inputs']['source_commitment'] for p in proofs]
        aggregated_commitment = hashlib.sha256(
            ''.join(all_commitments).encode()
        ).hexdigest()
        
        # Create aggregated proof
        aggregated_proof = {
            'pi_a': hashlib.sha256(''.join(p['proof']['pi_a'] for p in proofs).encode()).hexdigest()[:64],
            'pi_b': hashlib.sha256(''.join(p['proof']['pi_b'] for p in proofs).encode()).hexdigest()[:64],
            'pi_c': hashlib.sha256(''.join(p['proof']['pi_c'] for p in proofs).encode()).hexdigest()[:64],
            'protocol': 'groth16_aggregated'
        }
        
        return {
            'proof': aggregated_proof,
            'public_inputs': {
                'ioc_count': len(iocs),
                'ioc_hashes': [hashlib.sha256(ioc.encode()).hexdigest() for ioc in iocs],
                'aggregated_commitment': aggregated_commitment
            },
            'proof_count': len(proofs),
            'aggregated_at': datetime.now().isoformat()
        }


class IOCRegistry:
    """Registry for IOCs with zero-knowledge proofs"""
    
    def __init__(self):
        self.zk_system = ZKProofSystem()
        self.registry = {}  # In production: blockchain smart contract
        
    def submit_ioc(self, ioc: str, source: str, 
                   metadata: Dict = None) -> Dict[str, Any]:
        """Submit IOC with zero-knowledge proof"""
        
        # Generate proof
        proof_data = self.zk_system.generate_ioc_proof(ioc, source)
        
        # Create registry entry
        ioc_hash = proof_data['public_inputs']['ioc_hash']
        
        entry = {
            'ioc_hash': ioc_hash,
            'proof': proof_data['proof'],
            'public_inputs': proof_data['public_inputs'],
            'metadata': metadata or {},
            'submitted_at': datetime.now().isoformat(),
            'verified': False
        }
        
        # Verify proof before storing
        verification = self.zk_system.verify_ioc_proof(proof_data)
        
        if verification['valid']:
            entry['verified'] = True
            self.registry[ioc_hash] = entry
            
            return {
                'success': True,
                'ioc_hash': ioc_hash,
                'proof_verified': True,
                'registry_id': ioc_hash[:16]
            }
        else:
            return {
                'success': False,
                'reason': verification.get('reason', 'Verification failed')
            }
    
    def query_ioc(self, ioc: str) -> Dict[str, Any]:
        """Query if IOC exists in registry (without revealing sources)"""
        ioc_hash = hashlib.sha256(ioc.encode()).hexdigest()
        
        if ioc_hash in self.registry:
            entry = self.registry[ioc_hash]
            
            return {
                'found': True,
                'ioc_hash': ioc_hash,
                'verified': entry['verified'],
                'submitted_at': entry['submitted_at'],
                'proof_exists': True,
                # Note: source is NOT revealed
                'metadata': entry.get('metadata', {})
            }
        else:
            return {
                'found': False,
                'ioc_hash': ioc_hash
            }
    
    def get_stats(self) -> Dict[str, Any]:
        """Get registry statistics"""
        verified_count = sum(1 for e in self.registry.values() if e['verified'])
        
        return {
            'total_iocs': len(self.registry),
            'verified_iocs': verified_count,
            'unverified_iocs': len(self.registry) - verified_count
        }


if __name__ == "__main__":
    print("[*] Testing Zero-Knowledge Proof System\n")
    
    zk = ZKProofSystem()
    
    # Test 1: Generate proof
    print("[1] Generating ZK proof for IOC...")
    ioc = "192.168.1.100"
    source = "Sentinel_Org_Alpha"  # This stays private
    
    proof_data = zk.generate_ioc_proof(ioc, source)
    print(f"✓ Proof generated")
    print(f"  IOC: {ioc}")
    print(f"  Source commitment: {proof_data['public_inputs']['source_commitment'][:16]}...")
    print(f"  Proof: {proof_data['proof']['pi_a'][:16]}...")
    
    # Test 2: Verify proof
    print(f"\n[2] Verifying ZK proof...")
    verification = zk.verify_ioc_proof(proof_data)
    print(f"✓ Verification: {'VALID' if verification['valid'] else 'INVALID'}")
    print(f"  IOC hash: {verification.get('ioc_hash', 'N/A')[:16]}...")
    
    # Test 3: IOC Registry
    print(f"\n[3] Testing IOC Registry...")
    registry = IOCRegistry()
    
    # Submit IOC
    result = registry.submit_ioc(
        ioc="malicious.example.com",
        source="Sentinel_Org_Beta",
        metadata={'type': 'domain', 'severity': 'high'}
    )
    print(f"✓ IOC submitted: {result['success']}")
    print(f"  Registry ID: {result.get('registry_id', 'N/A')}")
    
    # Query IOC
    query_result = registry.query_ioc("malicious.example.com")
    print(f"✓ IOC query: {'Found' if query_result['found'] else 'Not found'}")
    print(f"  Verified: {query_result.get('verified', False)}")
    
    # Stats
    stats = registry.get_stats()
    print(f"\n✓ Registry Stats:")
    print(f"  Total IOCs: {stats['total_iocs']}")
    print(f"  Verified: {stats['verified_iocs']}")
    
    print(f"\n✓ All ZK proof tests passed!")
