"""
Clickjacking Checker
- X-Frame-Options header analysis
- Content-Security-Policy frame-ancestors directive
- Checks all subpages (login, admin, payment paths)
- Generates PoC HTML iframe snippet
"""

import re
import logging
import requests
from modules.utils import tor_session

logger = logging.getLogger(__name__)

HIGH_VALUE_PATHS = [
    '/', '/login', '/signin', '/admin', '/dashboard',
    '/account', '/profile', '/settings', '/payment',
    '/checkout', '/transfer', '/send', '/confirm',
    '/change-password', '/delete-account', '/api/v1',
]


class ClickjackingChecker:

    def run(self, domain: str) -> dict:
        result = {
            'domain': domain,
            'findings': [],
            'vulnerable_pages': [],
            'total': 0,
            'risk_level': 'LOW',
            'poc_html': '',
            'error': None,
        }

        session = tor_session()
        session.verify = False
        session.headers['User-Agent'] = 'Mozilla/5.0'

        for path in HIGH_VALUE_PATHS:
            for scheme in ('https', 'http'):
                url = f"{scheme}://{domain}{path}"
                try:
                    r = session.get(url, timeout=7, allow_redirects=True)
                    if r.status_code not in (200, 401, 403):
                        break

                    xfo = r.headers.get('X-Frame-Options', '').upper()
                    csp = r.headers.get('Content-Security-Policy', '')
                    fa  = self._extract_frame_ancestors(csp)

                    vuln, severity, detail = self._assess(path, xfo, fa)

                    if vuln:
                        finding = {
                            'severity': severity,
                            'url': url,
                            'path': path,
                            'x_frame_options': xfo or 'NOT SET',
                            'csp_frame_ancestors': fa or 'NOT SET',
                            'detail': detail,
                        }
                        result['findings'].append(finding)
                        result['vulnerable_pages'].append(url)

                    break  # https worked, skip http
                except Exception:
                    pass

        result['total'] = len(result['findings'])

        if result['vulnerable_pages']:
            result['poc_html'] = self._build_poc(domain, result['vulnerable_pages'][0])

        if any(f['severity'] == 'CRITICAL' for f in result['findings']):
            result['risk_level'] = 'CRITICAL'
        elif any(f['severity'] == 'HIGH' for f in result['findings']):
            result['risk_level'] = 'HIGH'
        elif result['findings']:
            result['risk_level'] = 'MEDIUM'

        return result

    def _extract_frame_ancestors(self, csp: str) -> str:
        m = re.search(r'frame-ancestors\s+([^;]+)', csp, re.IGNORECASE)
        return m.group(1).strip() if m else ''

    def _assess(self, path: str, xfo: str, fa: str):
        is_sensitive = any(k in path for k in
                           ('login', 'admin', 'payment', 'checkout',
                            'transfer', 'confirm', 'password', 'delete'))

        # Protected
        if xfo in ('DENY', 'SAMEORIGIN') or (fa and fa not in ("'none'", '*', '')):
            return False, None, None

        # Completely unprotected
        if not xfo and not fa:
            sev = 'HIGH' if is_sensitive else 'MEDIUM'
            detail = 'No X-Frame-Options and no CSP frame-ancestors — page can be framed'
            return True, sev, detail

        # Weak XFO
        if xfo == 'ALLOW-FROM':
            return True, 'MEDIUM', 'X-Frame-Options: ALLOW-FROM is deprecated and ignored by modern browsers'

        # CSP allows all origins
        if fa == '*':
            sev = 'HIGH' if is_sensitive else 'MEDIUM'
            return True, sev, "CSP frame-ancestors: * — any origin can frame this page"

        return False, None, None

    def _build_poc(self, domain: str, url: str) -> str:
        return f"""<!-- Clickjacking PoC — The Sentinel Pro -->
<html><body style="background:#1a1a2e;color:#fff;font-family:monospace;padding:20px">
<h2 style="color:#e74c3c">⚠ Clickjacking PoC — {domain}</h2>
<p>Target: <a href="{url}" style="color:#58a6ff">{url}</a></p>
<div style="position:relative;width:800px;height:600px;border:2px solid #e74c3c">
  <iframe src="{url}" style="width:800px;height:600px;border:none;opacity:0.5"></iframe>
  <div style="position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);
              background:rgba(231,76,60,0.8);padding:20px;border-radius:8px;text-align:center">
    <h3>Click Here to Win a Prize!</h3>
    <button style="padding:10px 20px;font-size:16px">CLICK ME</button>
  </div>
</div>
<p style="color:#8b949e;font-size:12px">Generated by The Sentinel Pro</p>
</body></html>"""
